### PR TITLE
Url plugin should match ambient.d.ts

### PR DESCRIPTION
**Pull request by bjon**
Fixed jpeg and webp imports from `src/node_modules/images`.

### CODE REVIEW

**Comment by benmccann** [comment]
I'm not sure why `@rollup/plugin-url` doesn't include these by default, but that seems like a better place for this change

If we were going to override the default I would think we should just include the whole `images` directory rather than specifying file types

**Comment by bjon** [comment]
@benmccann :+1:

**Comment by bjon** [comment]
@benmccann btw, did you mean I should do a PR in plugin-url instead?

**Comment by benmccann** [comment]
If you'd like

**Comment by bjon** [comment]
I opened a PR in URL plugin instead

**Comment by benmccann** [comment]
Ok. I'll go ahead and close this one since it looks like the PR to the URL plugin has been approved

**Comment by bjon** [comment]
:+1:

**Pull request closed without merging**
