### PR TITLE
fix: hot reload for webpack template

### PR DESCRIPTION
**Pull request by alireza-mh**
It will solve this issue #675 which I faced in my repo as well.

### CODE REVIEW

**Comment by benmccann** [comment]
Can you please link to the issue?

**Comment by alireza-mh** [comment]
Sure.

https://github.com/sveltejs/sapper/issues/675

**Comment by Conduitry** [comment]
PRs need to be made against the master branch. The rollup and webpack branches are automatically generated from the master branch and force pushed.

**Comment by alireza-mh** [comment]
Thanks, I didn't know. I opened a new one  #272.

**Pull request closed without merging**
