### PR TITLE
[WIP] Svelte v3

### PR DESCRIPTION
**Pull request by malkomalko**
This is a work in progress...

### CODE REVIEW

**Comment by thgh** [comment]
Maybe a good time to introduce `prettier`?

**Comment by malkomalko** [comment]
Initial load is working well but hitting two errors when trying to navigate:

image

and

image

**Comment by malkomalko** [comment]
I've tracked the erroring line down to https://github.com/sveltejs/svelte/blob/master/src/internal/Component.js#L107

It looks like it's being called from https://github.com/ekhaled/svelte-dev-helper/blob/master/lib/proxy.js#L128.  Looks like `svelte-dev-helper` is required by `svelte-loader` so maybe that library needs to be updated as well?

**Comment by Sh1d0w** [comment]
Any plans to merge this? Currently Sapper is using old version of Svelte and we are holding back to start a new project with it, until we can use the latest version.

**Comment by Conduitry** [comment]
This is intentionally not being merged yet. We're waiting until the corresponding version of Sapper is in a bit more of a finished state and we have the chance to update its documentation.

**Comment by Conduitry** [comment]
There are other official `v3-rollup` and `v3-webpack` branches on this repo which can be used right now.

**Pull request closed without merging**
