### PR TITLE
Replace Borat pic with Success Kid

### LINKED ISSUE #185: Can we change the Borat picture?
Hi, I just started with Svelte & Sapper, love the concepts, and it's been really nice to use Svelte so far.

At first I thought the sample's borat image was funny, but the more time passed, the more it left a bad taste in my mouth. The borat quotes I remember are all gross.

I don't think it puts this framework on a good first foot with beginners to have that image there.
There are a million other fun images to put there to make a better first impression.

eg an alternative is the [Success Kid Meme](https://imgflip.com/memegenerator/Success-Kid)

here's one https://i.imgflip.com/3j2nq8.jpg

### PR DESCRIPTION
**Pull request by amedeedaboville**
Fixes #185.

Changes the picture to Success Kid, and the caption from `High Five` to `Have fun with Sapper!`

Thanks for looking at it @pngwn

### CODE REVIEW

**Comment by amedeedaboville** [comment]
Ok, fixed. I replaced the png with a 76kb jpeg which looks the same.

**Comment by arxpoetica** [comment]
We can't use the Sammy Griner success meme picture—it's licensed by his mother and she's successfully sued and won in various cases: https://en.m.wikipedia.org/wiki/Success_Kid

Let's use our own branding somehow.

I'm going to close this PR and put together one w/ the Svelte `S`.

**Comment by pngwn** [comment]
It’s licensed for commercial use. I don’t think we would be in any danger here, at worst we might get a letter telling us to remove it.

**Comment by arxpoetica** [comment]
Fair enough.

**Comment by qm3ster** [comment]
Can we have an SVG instead?
If not Borat, then obviously Sapper logo.
But not a crusty JPEG, please.
(I am aware Borat was a PNG)

**Comment by Conduitry** [comment]
Your mom's crusty

**Pull request merged**
