### PR TITLE
Pwa audit/add meta description to routes

### PR DESCRIPTION
**Pull request by mellisdesigns**
**Summary**
Add `meta` descriptions to all routes in the generated sample template based off Lighthouse Audit recommendations.

**Audit Trail**
_After_
image

_Before_
image

### CODE REVIEW

**Comment by mellisdesigns** [comment]
Excuse the name of the branch, this is not a pws specific change. As part of this PR I can also change a few other items that the audit picked up. Thoughts?

**Comment by evdama** [comment]
that's the issue that goes along with this https://github.com/sveltejs/svelte/issues/1607

**Comment by evdama** [comment]
something odd is going on, based of the template, when I apply this patch, then npm install and npm run build and npm run dev it renders fine but just for the initial load. After that, clicking between the items inside Nav doesn't show the route contents e.g. try clicking 'about' or 'blog' and back to 'home'. Nothing is rendered.

**Comment by matyunya** [comment]
Adding meta to `<svelte:head>` breaks page transitions for me.

**Comment by evdama** [comment]
yup, it does, so it's verified

**Comment by Conduitry** [comment]
See https://github.com/sveltejs/svelte/issues/3187#issuecomment-508942887 - I believe this is a bug that needs to be fixed in Svelte, not worked around in Sapper.

**Comment by benmccann** [comment]
It looks like it was fixed in Svelte 3.6.7

**Comment by benmccann** [comment]
I'm going to close this since we're now on a newer version of Svelte

**Pull request closed without merging**
